name: activsy
description: reacts when there are no user activities in your application
version: 1.0.0
homepage: https://github.com/EdvaldoMartins/activsy
repository: https://github.com/EdvaldoMartins/activsy
issue_tracker: https://github.com/EdvaldoMartins/activsy/issues

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: activsy
      ios:
        default_package: activsy
      web:
        default_package: activsy
      macos:
        default_package: activsy
      windows:
        default_package: activsy
      linux:
        default_package: activsy